
import "./globals.css";
import Header from "@/src/components/Header";
import { Work_Sans } from "next/font/google";

const workSans = Work_Sans({
  subsets: ["latin"],
  weight: ["400", "700"], // Adicione os pesos desejados
  variable: "--font-work-sans", // Cria uma variável CSS
});


export const metadata = {
  title: "Página de Comida",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt">
      <body className={workSans.className}>
        <Header />
        {children}
      </body>
    </html>
  );
}
